server:
  port: 8080

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql : true

#JWT Hashing Key
jwt.secretkey-value: rejgieorjgioregjnoiernoiejgioerjhioethjiojieoqfjiweofjwioghueorhnweofi